# Configurações gerais
server:
    port: 8080


# Configurações OpenFeign
feign:
    imdb:
        url: http://www.omdbapi.com/
        name: imdb


# Configurações H2 - Banco de Dados em Memória:
spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password: sa
        url: jdbc:h2:./data/db
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher


# Informações gerais:
info:
    app:
        description: '@project.description@'
        encoding: '@project.build.sourceEncoding@'
        java.version: '@java.version@'
        name: '@project.name@'
        version: '@project.version@'